title: Jian(Tim) Shen
logo: "/images/Logo.png?raw=true"
# logo: "/images/My.png?raw=true"
description: > 
  Hi, I'm Tim S, nice to meet you. 
  <br><br>
  
  <br><br>
  <a href="https://www.linkedin.com/in/jian-tim-shen/">LinkedIn Profile</a> 
  <br><br>
  <a href="https://en.wikipedia.org/wiki/Bellman_equation">Logo - Bellman Equation</a>
theme: jekyll-theme-minimal
